# .github/workflows/tag-trigger.yml
name: Tag Trigger Workflow

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build or test steps here
      - name: Run build
        run: echo "Running build for tag ${{ github.ref }}"

      - name: Create release tag
        run: |
          TAG_NAME=${{ github.ref }}
          RELEASE_TAG=v${TAG_NAME#refs/tags/}
          git tag $RELEASE_TAG
          git push origin $RELEASE_TAG
