# .github/workflows/tag-trigger.yml
name: Tag Trigger Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build or test steps here
      - name: Run build
        run: echo "Running build for tag ${{ github.ref }}"
