name: Build and Test

on:
  push:
    tags:
      - "v+[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          token: ${{ secrets.GH_TOKEN }}
          generate_release_notes: true
          make_latest: true

      - name: Save tag to file
        run: echo "${{ github.ref }}" > release-tag.txt

      - name: Upload tag artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-tag
          path: release-tag.txt
