name: Deploy App

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build or test steps here
      - name: Run build
        run: echo "Running deployment for tag ${{ github.ref }}"
