name: Create Release

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List artifacts available for download
        run: ls -al

      - name: Download tag artifact
        uses: actions/download-artifact@v3
        with:
          name: release-tag

      - name: Show contents of downloaded artifact
        run: cat release-tag.txt

      - name: Read tag
        id: read_tag
        run: |
          TAG=$(cat release-tag.txt)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Use tag
        run: echo "Using tag ${{ env.TAG }}"
